---
services:
  smi2mqtt:
    container_name: smi2mqtt
    image: gitea.rh-sky.de/robin/smi2mqtt:latest
    volumes:
      - ./data:/opt/smi2mqtt
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
...